version: "3.8"
services:
  postgres_db:
    image: postgres:16
    container_name: gscores_postgres
    environment:
      POSTGRES_USER: gscores
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gscores_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
